"""add videos

Revision ID: b6ce674f3cb0
Revises: 
Create Date: 2017-05-21 10:45:58.095330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ce674f3cb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_description', sa.Text(), nullable=True),
    sa.Column('video_img', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('vedio_digg_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_video_url'), 'videos', ['video_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_video_url'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
